import { spawn, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  copyFileSync,
  cpSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const nativeRoot = resolve(repositoryRoot, "native", "windows-job-helper");
const windowsIt = it.runIf(process.platform === "win32");
const nativeBuildActions = [
  "preflight",
  "test-managed",
  "test-kernel",
  "verify",
  "update-artifact",
  "test",
] as const;
type NativeBuildAction = (typeof nativeBuildActions)[number];

const expectedGeneratedProtocolConstants = `// <auto-generated />
namespace CodexAgentTools.WindowsJobHelper
{
    internal static class ProtocolV1
    {
        internal const string ControlMode = "--control-v1";
        internal const string ProbeMode = "--probe-v1";
        internal const string Magic = "CAJ1";
        internal const int Version = 1;
        internal const int HeaderBytes = 12;
        internal const int MaxPayloadBytes = 1048576;
        internal const int MaxStringBytes = 65536;
        internal const int MaxArgCount = 1024;
        internal const int MaxNativeCommandLineUtf16UnitsIncludingNul = 32767;
        internal const int MessageLaunchConfig = 1;
        internal const int MessageReady = 2;
        internal const int MessageTerminate = 3;
        internal const int MessageError = 4;
        internal const int MessageExit = 5;
        internal const int ReasonNoneOrRootExit = 0;
        internal const int ReasonCancelled = 1;
        internal const int ReasonTimedOut = 2;
        internal const int ReasonSessionShutdown = 3;
        internal const int ReasonProtocolError = 4;
        internal const int StageProtocolInvalid = 1;
        internal const int StageCancelledBeforeReady = 2;
        internal const int StageJobCreateFailed = 3;
        internal const int StageJobConfigFailed = 4;
        internal const int StageStdioDuplicateFailed = 5;
        internal const int StageAttributeListInitFailed = 6;
        internal const int StageHandleListAttributeFailed = 7;
        internal const int StageJobListAttributeFailed = 8;
        internal const int StageCommandLineInvalid = 9;
        internal const int StageCreateFailed = 10;
        internal const int StageResumeFailed = 11;
        internal const int StageTerminateJobFailed = 12;
        internal const int StageQueryJobFailed = 13;
        internal const int StageControlChannelFailed = 14;
        internal const int StageHelperInternal = 15;
        internal const int StageWaitFailed = 16;
    }
}
`;
const expectedGeneratedProtocolSha256 =
  "0611bac55aeb67c5aa0bad23bd23e4cd6503fd56495d0d5d9b13f6d61a357d04";

function readRepositoryFile(path: string): string {
  return readFileSync(resolve(repositoryRoot, path), "utf8");
}

function readRepositoryJson(path: string): unknown {
  return JSON.parse(readRepositoryFile(path));
}

function run(
  executable: string,
  arguments_: readonly string[],
  options: { cwd?: string; env?: NodeJS.ProcessEnv } = {},
) {
  return spawnSync(executable, arguments_, {
    cwd: options.cwd ?? repositoryRoot,
    env: options.env,
    encoding: "utf8",
    windowsHide: true,
  });
}

function runPowerShell(
  script: string,
  action: NativeBuildAction,
  environment?: NodeJS.ProcessEnv,
) {
  return run(
    "powershell.exe",
    [
      "-NoLogo",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      script,
      "-Action",
      action,
    ],
    environment === undefined ? {} : { env: environment },
  );
}

function runRestore(script: string, environment?: NodeJS.ProcessEnv) {
  return run(
    "powershell.exe",
    [
      "-NoLogo",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      script,
    ],
    environment === undefined ? {} : { env: environment },
  );
}

function sha256(contents: Uint8Array): string {
  return createHash("sha256").update(contents).digest("hex");
}

function digest(path: string, algorithm: "sha256" | "sha512"): string {
  return createHash(algorithm).update(readFileSync(path)).digest("hex");
}

function runAsync(
  executable: string,
  arguments_: readonly string[],
  options: { cwd?: string; env?: NodeJS.ProcessEnv } = {},
): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(executable, arguments_, {
      cwd: options.cwd ?? repositoryRoot,
      env: options.env,
      windowsHide: true,
      stdio: ["ignore", "pipe", "pipe"],
    });
    const stdout: Buffer[] = [];
    const stderr: Buffer[] = [];
    child.stdout.on("data", (chunk: Buffer) => stdout.push(chunk));
    child.stderr.on("data", (chunk: Buffer) => stderr.push(chunk));
    child.once("error", reject);
    child.once("close", (status) =>
      resolvePromise({
        status,
        stdout: Buffer.concat(stdout).toString("utf8"),
        stderr: Buffer.concat(stderr).toString("utf8"),
      }),
    );
  });
}

function runPowerShellAsync(
  script: string,
  action: NativeBuildAction,
  environment: NodeJS.ProcessEnv,
) {
  return runAsync(
    "powershell.exe",
    [
      "-NoLogo",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      script,
      "-Action",
      action,
    ],
    { env: environment },
  );
}

function runRestoreAsync(script: string, environment: NodeJS.ProcessEnv) {
  return runAsync(
    "powershell.exe",
    [
      "-NoLogo",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      script,
    ],
    { env: environment },
  );
}

function writeFixtureFile(path: string, contents: Uint8Array | string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}

function buildInvocationRoots(systemTemp: string): string[] {
  const buildBase = join(
    systemTemp,
    "codex-agent-tools",
    "windows-job-helper",
    "build-v1",
  );
  try {
    return readdirSync(buildBase, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => join(buildBase, entry.name))
      .sort();
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return [];
    }
    throw error;
  }
}

function createTinyToolchainFixture(fixtureRoot: string) {
  const scriptRoot = join(fixtureRoot, "script");
  const systemTemp = join(fixtureRoot, "system-temp");
  const cacheRoot = join(
    systemTemp,
    "codex-agent-tools",
    "windows-job-helper",
    "toolchain-v1",
  );
  const archiveRoot = join(cacheRoot, "archives");
  mkdirSync(scriptRoot);
  mkdirSync(archiveRoot, { recursive: true });
  copyFileSync(
    resolve(nativeRoot, "restore-toolchain.ps1"),
    join(scriptRoot, "restore-toolchain.ps1"),
  );

  const packages = [
    {
      id: "Microsoft.Net.Compilers.Toolset",
      version: "4.14.0",
      files: {
        "tasks/net472/csc.exe": Buffer.from("tiny-csc\0\r\n", "utf8"),
        "tasks/net472/support.dat": Buffer.from("support", "utf8"),
      },
    },
    {
      id: "Microsoft.NETFramework.ReferenceAssemblies.net48",
      version: "1.0.3",
      files: {
        "build/.NETFramework/v4.8/mscorlib.dll": Buffer.from("mscorlib", "utf8"),
        "build/.NETFramework/v4.8/System.dll": Buffer.from("system", "utf8"),
        "build/.NETFramework/v4.8/System.Core.dll": Buffer.from("system-core", "utf8"),
      },
    },
  ];
  const zipScript = join(fixtureRoot, "create-zip.ps1");
  writeFileSync(
    zipScript,
    [
      "param([string]$Source, [string]$Destination)",
      "Set-StrictMode -Version Latest",
      "$ErrorActionPreference = 'Stop'",
      "Add-Type -AssemblyName System.IO.Compression",
      "Add-Type -AssemblyName System.IO.Compression.FileSystem",
      "$archive = [System.IO.Compression.ZipFile]::Open($Destination, [System.IO.Compression.ZipArchiveMode]::Create)",
      "try {",
      "  $root = [System.IO.Path]::GetFullPath($Source).TrimEnd('\\', '/') + '\\'",
      "  foreach ($file in Get-ChildItem -LiteralPath $Source -Recurse -File | Sort-Object FullName) {",
      "    $relative = $file.FullName.Substring($root.Length).Replace('\\', '/')",
      "    $entry = $archive.CreateEntry($relative, [System.IO.Compression.CompressionLevel]::Optimal)",
      "    $input = $file.OpenRead()",
      "    $output = $entry.Open()",
      "    try { $input.CopyTo($output) } finally { $output.Dispose(); $input.Dispose() }",
      "  }",
      "} finally { $archive.Dispose() }",
      "",
    ].join("\n"),
  );

  const lockPackages = packages.map((fixturePackage) => {
    const source = join(fixtureRoot, "archive-source", fixturePackage.id);
    for (const [relativePath, contents] of Object.entries(fixturePackage.files)) {
      writeFixtureFile(join(source, ...relativePath.split("/")), contents);
    }
    const archiveName = `${fixturePackage.id.toLowerCase()}.${fixturePackage.version}.nupkg`;
    const archivePath = join(archiveRoot, archiveName);
    const zipResult = run("powershell.exe", [
      "-NoLogo",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      zipScript,
      "-Source",
      source,
      "-Destination",
      archivePath,
    ]);
    expect(zipResult.status, zipResult.stderr).toBe(0);
    return {
      id: fixturePackage.id,
      version: fixturePackage.version,
      url: `https://example.invalid/${archiveName}`,
      byteLength: statSync(archivePath).size,
      sha256: digest(archivePath, "sha256"),
      sha512: digest(archivePath, "sha512"),
    };
  });
  writeFileSync(
    join(scriptRoot, "toolchain.lock.json"),
    `${JSON.stringify({ schemaVersion: 1, nugetPackages: lockPackages }, null, 2)}\n`,
  );
  return {
    scriptRoot,
    systemTemp,
    cacheRoot,
    environment: { ...process.env, TEMP: systemTemp, TMP: systemTemp },
  };
}

describe("Windows native helper build contract", () => {
  it("pins only the exact official NuGet packages", () => {
    expect(
      readRepositoryJson("native/windows-job-helper/toolchain.lock.json"),
    ).toEqual({
      schemaVersion: 1,
      nugetPackages: [
        {
          id: "Microsoft.Net.Compilers.Toolset",
          version: "4.14.0",
          url: "https://api.nuget.org/v3-flatcontainer/microsoft.net.compilers.toolset/4.14.0/microsoft.net.compilers.toolset.4.14.0.nupkg",
          byteLength: 21_771_766,
          sha256:
            "941a9cf3ea618d88d01a3dd6b1a45a06bcf07716a9f81ce4031caa3edd24a845",
          sha512:
            "879184c42ddfc747e6d2a1f0f2b43acb9734ba4e9c0a202ca2b2e5f47abff55968b44becbffa16eb444da3c1ce600a6feba90da89ab8060fd391202c8100306d",
        },
        {
          id: "Microsoft.NETFramework.ReferenceAssemblies.net48",
          version: "1.0.3",
          url: "https://api.nuget.org/v3-flatcontainer/microsoft.netframework.referenceassemblies.net48/1.0.3/microsoft.netframework.referenceassemblies.net48.1.0.3.nupkg",
          byteLength: 20_997_929,
          sha256:
            "8a7e348538e7eb91351696911689f49e3d4f63f8bab517432bbe159b8b1104a2",
          sha512:
            "5d62a0c9e35a74d71341a215bd007c06b74236b11aafa7e8fdd7b539d41167d1c5cb48dc05268cf08579abae196a6a6c4a70bc0254ec002686654ba8170e3544",
        },
      ],
    });
  });

  it("pins deterministic x64 compiler inputs and system-temporary output", () => {
    const config = readRepositoryJson(
      "native/windows-job-helper/build.config.json",
    ) as {
      sourceSets: Record<string, string[]>;
    };

    expect(config).toEqual({
      schemaVersion: 1,
      targetFramework: "net48",
      configuration: "Release",
      platform: "x64",
      compilerArguments: [
        "/noconfig",
        "/nostdlib+",
        "/target:exe",
        "/platform:x64",
        "/optimize+",
        "/debug-",
        "/deterministic+",
        "/checked+",
        "/unsafe-",
        "/langversion:latest",
        "/utf8output",
        "/filealign:512",
      ],
      references: ["mscorlib.dll", "System.dll", "System.Core.dll"],
      pathMap: {
        sourceRoot: "native/windows-job-helper",
        virtualRoot: "/_/native/windows-job-helper",
      },
      sourceSets: {
        preflight: ["src/Fd3Preflight.cs"],
        production: [],
        managedTests: [],
        kernelTests: [],
        fixtures: [],
      },
      output: {
        root: "system-temp",
        repositoryOutputsForbidden: true,
      },
      generatedProtocolConstants: {
        relativePath: "generated/ProtocolV1.g.cs",
        sha256: expectedGeneratedProtocolSha256,
      },
    });

    for (const sources of Object.values(config.sourceSets)) {
      expect(sources).toEqual([...sources].sort((left, right) => left.localeCompare(right)));
      expect(sources.every((source) => !source.includes("\\") && !source.startsWith("/"))).toBe(
        true,
      );
    }
  });

  it("fixes LF text checkout and excludes PE files from text conversion", () => {
    expect(readRepositoryFile(".gitattributes")).toBe(
      "* text=auto eol=lf\n*.exe binary\n",
    );
  });

  it("proves LF text and byte-identical PE data through real autocrlf checkouts", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "cat-native-eol-"));
    const source = join(fixtureRoot, "source");
    const expectedText = Buffer.from("first\nsecond\n", "utf8");
    const expectedExe = Buffer.from([
      0x4d, 0x5a, 0x00, 0x0d, 0x0a, 0x1a, 0x0a, 0xff, 0x0d, 0x0a,
    ]);
    try {
      mkdirSync(source);
      copyFileSync(resolve(repositoryRoot, ".gitattributes"), join(source, ".gitattributes"));
      writeFileSync(join(source, "fixture.txt"), expectedText);
      writeFileSync(join(source, "fixture.exe"), expectedExe);
      for (const arguments_ of [
        ["init", "--quiet"],
        ["config", "user.email", "native-test@example.invalid"],
        ["config", "user.name", "Native Test"],
        ["add", ".gitattributes", "fixture.txt", "fixture.exe"],
        ["commit", "--quiet", "-m", "fixture"],
      ]) {
        const result = run("git", arguments_, { cwd: source });
        expect(result.status, result.stderr).toBe(0);
      }

      for (const autocrlf of ["true", "false"]) {
        const checkout = join(fixtureRoot, `checkout-${autocrlf}`);
        let result = run("git", ["clone", "--quiet", "--no-checkout", source, checkout]);
        expect(result.status, result.stderr).toBe(0);
        result = run("git", ["config", "core.autocrlf", autocrlf], { cwd: checkout });
        expect(result.status, result.stderr).toBe(0);
        result = run("git", ["checkout", "--quiet", "--force", "HEAD"], { cwd: checkout });
        expect(result.status, result.stderr).toBe(0);
        expect(readFileSync(join(checkout, "fixture.txt"))).toEqual(expectedText);
        expect(readFileSync(join(checkout, "fixture.exe"))).toEqual(expectedExe);
      }
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  windowsIt(
    "generates exact protocol constants for every action and rejects canonical drift",
    async () => {
      expect(sha256(Buffer.from(expectedGeneratedProtocolConstants, "utf8"))).toBe(
        expectedGeneratedProtocolSha256,
      );

      const cases: Array<{
        name: string;
        mutate?: (protocol: Record<string, unknown>) => void;
      }> = [
        { name: "canonical" },
        {
          name: "extra-key",
          mutate: (protocol) => {
            protocol.extra = true;
          },
        },
        {
          name: "missing-key",
          mutate: (protocol) => {
            delete (protocol.frame as Record<string, unknown>).headerBytes;
          },
        },
        {
          name: "value-drift",
          mutate: (protocol) => {
            (protocol.reason as Record<string, unknown>).cancelled = 9;
          },
        },
      ];

      const fixtureRoot = mkdtempSync(join(tmpdir(), "cat-native-generate-actions-"));
      const systemTemp = join(fixtureRoot, "system-temp");
      mkdirSync(systemTemp);
      let canonicalScriptRoot = "";
      try {
        for (const testCase of cases) {
          const scriptRoot = join(fixtureRoot, `native-${testCase.name}`);
          if (testCase.mutate === undefined) {
            canonicalScriptRoot = scriptRoot;
          }
          mkdirSync(scriptRoot);
          for (const name of [
            "build.ps1",
            "build.config.json",
            "protocol.v1.json",
          ]) {
            copyFileSync(resolve(nativeRoot, name), join(scriptRoot, name));
          }
          writeFileSync(
            join(scriptRoot, "restore-toolchain.ps1"),
            "Write-Output 'restored'\n",
          );
          const protocol = JSON.parse(
            readFileSync(join(scriptRoot, "protocol.v1.json"), "utf8"),
          ) as Record<string, unknown>;
          testCase.mutate?.(protocol);
          writeFileSync(
            join(scriptRoot, "protocol.v1.json"),
            `${JSON.stringify(protocol, null, 2)}\n`,
          );

          const environment = { ...process.env, TEMP: systemTemp, TMP: systemTemp };
          for (const action of nativeBuildActions) {
            const before = buildInvocationRoots(systemTemp);
            const result = runPowerShell(
              join(scriptRoot, "build.ps1"),
              action,
              environment,
            );
            if (testCase.mutate === undefined) {
              expect(result.status, `${action}: ${result.stderr}`).toBe(1);
              expect(result.stderr).toContain(
                "native sources are not available for this action",
              );
              expect(result.stdout).toBe(
                "windows-native-helper: generated protocol constants verified\r\n",
              );
            } else {
              expect(result.status, `${testCase.name}/${action}`).toBe(1);
              expect(result.stderr).toContain("invalid protocol contract");
              expect(result.stdout).toBe("");
            }
            expect(buildInvocationRoots(systemTemp)).toEqual(before);
          }
        }

        const environment = { ...process.env, TEMP: systemTemp, TMP: systemTemp };
        const beforeConcurrent = new Set(buildInvocationRoots(systemTemp));
        const concurrent = await Promise.all([
          runPowerShellAsync(
            join(canonicalScriptRoot, "build.ps1"),
            "verify",
            environment,
          ),
          runPowerShellAsync(
            join(canonicalScriptRoot, "build.ps1"),
            "verify",
            environment,
          ),
        ]);
        for (const result of concurrent) {
          expect(result.status, result.stderr).toBe(1);
          expect(result.stderr).toContain(
            "native sources are not available for this action",
          );
          expect(result.stdout).toBe(
            "windows-native-helper: generated protocol constants verified\r\n",
          );
        }
        expect(buildInvocationRoots(systemTemp)).toEqual([...beforeConcurrent]);

        for (const boundary of ["temp-root", "build-parent"] as const) {
          const boundaryRoot = join(fixtureRoot, boundary);
          const outside = join(fixtureRoot, `${boundary}-outside`);
          mkdirSync(outside);
          let boundaryTemp: string;
          if (boundary === "temp-root") {
            boundaryTemp = join(fixtureRoot, "temp-junction");
            symlinkSync(outside, boundaryTemp, "junction");
          } else {
            boundaryTemp = boundaryRoot;
            mkdirSync(join(boundaryTemp, "codex-agent-tools"), { recursive: true });
            symlinkSync(
              outside,
              join(boundaryTemp, "codex-agent-tools", "windows-job-helper"),
              "junction",
            );
          }
          const result = runPowerShell(
            join(canonicalScriptRoot, "build.ps1"),
            "verify",
            { ...process.env, TEMP: boundaryTemp, TMP: boundaryTemp },
          );
          expect(result.status).toBe(1);
          expect(result.stderr).toContain("reparse point");
          expect(readdirSync(outside)).toEqual([]);
        }

        const cleanupAttackRoot = join(fixtureRoot, "cleanup-attack");
        const cleanupOutside = join(fixtureRoot, "cleanup-outside");
        mkdirSync(cleanupAttackRoot);
        mkdirSync(cleanupOutside);
        for (const name of ["build.ps1", "build.config.json", "protocol.v1.json"]) {
          copyFileSync(resolve(nativeRoot, name), join(cleanupAttackRoot, name));
        }
        writeFileSync(
          join(cleanupAttackRoot, "restore-toolchain.ps1"),
          [
            "$base = Join-Path $env:TEMP 'codex-agent-tools\\windows-job-helper\\build-v1'",
            "$root = @(Get-ChildItem -LiteralPath $base -Directory)[0]",
            "$outsideRoot = Join-Path $env:CAT_CLEANUP_OUTSIDE $root.Name",
            "[System.IO.Directory]::CreateDirectory($outsideRoot) | Out-Null",
            "[System.IO.File]::WriteAllText((Join-Path $outsideRoot 'sentinel.txt'), 'do-not-delete')",
            "[System.IO.Directory]::Move($base, $env:CAT_ORIGINAL_BUILD_BASE)",
            "New-Item -Path $base -ItemType Junction -Target $env:CAT_CLEANUP_OUTSIDE | Out-Null",
            "",
          ].join("\n"),
        );
        const originalBuildBase = join(fixtureRoot, "original-build-base");
        const attackResult = runPowerShell(
          join(cleanupAttackRoot, "build.ps1"),
          "verify",
          {
            ...process.env,
            TEMP: systemTemp,
            TMP: systemTemp,
            CAT_CLEANUP_OUTSIDE: cleanupOutside,
            CAT_ORIGINAL_BUILD_BASE: originalBuildBase,
          },
        );
        expect(attackResult.status).toBe(1);
        expect(attackResult.stderr).toContain(
          "windows-native-helper: native build cleanup failed",
        );
        const outsideGuids = readdirSync(cleanupOutside);
        expect(outsideGuids).toHaveLength(1);
        expect(
          readFileSync(join(cleanupOutside, outsideGuids[0] as string, "sentinel.txt"), "utf8"),
        ).toBe("do-not-delete");
        expect(readdirSync(originalBuildBase)).toHaveLength(1);

        const unknownAttackRoot = join(fixtureRoot, "unknown-attack");
        const unknownTemp = join(fixtureRoot, "unknown-temp");
        mkdirSync(unknownAttackRoot);
        mkdirSync(unknownTemp);
        for (const name of ["build.ps1", "build.config.json", "protocol.v1.json"]) {
          copyFileSync(resolve(nativeRoot, name), join(unknownAttackRoot, name));
        }
        writeFileSync(
          join(unknownAttackRoot, "restore-toolchain.ps1"),
          [
            "$base = Join-Path $env:TEMP 'codex-agent-tools\\windows-job-helper\\build-v1'",
            "$root = @(Get-ChildItem -LiteralPath $base -Directory)[0].FullName",
            "[System.IO.File]::WriteAllText((Join-Path $root 'unknown.txt'), 'preserve-evidence')",
            "",
          ].join("\n"),
        );
        const unknownResult = runPowerShell(
          join(unknownAttackRoot, "build.ps1"),
          "verify",
          { ...process.env, TEMP: unknownTemp, TMP: unknownTemp },
        );
        expect(unknownResult.status).toBe(1);
        expect(unknownResult.stderr).toContain(
          "windows-native-helper: native build cleanup failed",
        );
        const unknownRoots = buildInvocationRoots(unknownTemp);
        expect(unknownRoots).toHaveLength(1);
        expect(readFileSync(join(unknownRoots[0] as string, "unknown.txt"), "utf8")).toBe(
          "preserve-evidence",
        );

        const runnerFixture = join(fixtureRoot, "runner-fixture");
        const malicious = join(fixtureRoot, "malicious-path");
        mkdirSync(join(runnerFixture, "scripts"), { recursive: true });
        mkdirSync(join(runnerFixture, "native", "windows-job-helper"), {
          recursive: true,
        });
        mkdirSync(malicious);
        copyFileSync(
          resolve(repositoryRoot, "scripts", "windows-native-helper.mjs"),
          join(runnerFixture, "scripts", "windows-native-helper.mjs"),
        );
        writeFileSync(
          join(
            runnerFixture,
            "native",
            "windows-job-helper",
            "restore-toolchain.ps1",
          ),
          "Write-Output 'trusted-stub'\n",
        );
        copyFileSync(process.execPath, join(malicious, "powershell.exe"));
        const runner = join(runnerFixture, "scripts", "windows-native-helper.mjs");
        const secureResult = run(
          process.execPath,
          [runner, "restore"],
          {
            cwd: malicious,
            env: { ...process.env, PATH: malicious },
          },
        );
        expect(secureResult.status, secureResult.stderr).toBe(0);
        expect(secureResult.stdout).toContain("trusted-stub");
      } finally {
        rmSync(fixtureRoot, { recursive: true, force: true });
      }
    },
    120_000,
  );

  windowsIt(
    "rejects every expanded toolchain mutation without repairing the isolated cache",
    async () => {
      const fixtureRoot = mkdtempSync(join(tmpdir(), "cat-native-restore-"));
      try {
        const fixture = createTinyToolchainFixture(fixtureRoot);
        const { scriptRoot, environment, cacheRoot } = fixture;
        const restoreScript = join(scriptRoot, "restore-toolchain.ps1");
        const packageRoot = join(cacheRoot, "packages");

        const escapedTemporaryRoot = join(fixtureRoot, "restore-temp-junction");
        const escapedTemporaryTarget = join(fixtureRoot, "restore-temp-outside");
        mkdirSync(escapedTemporaryTarget);
        symlinkSync(escapedTemporaryTarget, escapedTemporaryRoot, "junction");
        const escapedResult = runRestore(restoreScript, {
          ...process.env,
          TEMP: escapedTemporaryRoot,
          TMP: escapedTemporaryRoot,
        });
        expect(escapedResult.status).toBe(1);
        expect(escapedResult.stderr).toContain("reparse point");
        expect(readdirSync(escapedTemporaryTarget)).toEqual([]);

        const restoreFresh = () => {
          rmSync(packageRoot, { recursive: true, force: true });
          const result = runRestore(restoreScript, environment);
          expect(result.status, result.stderr).toBe(0);
        };
        restoreFresh();

        const compiler = join(
          packageRoot,
          "microsoft.net.compilers.toolset.4.14.0",
          "tasks",
          "net472",
          "csc.exe",
        );
        const originalCompiler = readFileSync(compiler);
        const corruptedCompiler = Buffer.from(originalCompiler);
        const lastByte = corruptedCompiler.length - 1;
        corruptedCompiler.writeUInt8(
          corruptedCompiler.readUInt8(lastByte) ^ 0xff,
          lastByte,
        );
        writeFileSync(compiler, corruptedCompiler);
        let result = runRestore(restoreScript, environment);
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("expanded toolchain content mismatch");
        expect(readFileSync(compiler)).toEqual(corruptedCompiler);

        restoreFresh();
        const extra = join(
          packageRoot,
          "microsoft.net.compilers.toolset.4.14.0",
          "unexpected.bin",
        );
        writeFileSync(extra, "unexpected");
        result = runRestore(restoreScript, environment);
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("expanded toolchain file set mismatch");
        expect(readFileSync(extra, "utf8")).toBe("unexpected");

        restoreFresh();
        unlinkSync(compiler);
        result = runRestore(restoreScript, environment);
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("expanded toolchain file set mismatch");
        expect(() => readFileSync(compiler)).toThrow();

        restoreFresh();
        const tasks = dirname(dirname(compiler));
        const outsideTasks = join(fixtureRoot, `outside-${basename(tasks)}`);
        cpSync(tasks, outsideTasks, { recursive: true });
        rmSync(tasks, { recursive: true, force: true });
        symlinkSync(outsideTasks, tasks, "junction");
        result = runRestore(restoreScript, environment);
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("reparse point");

        rmSync(tasks, { recursive: true, force: true });
        rmSync(packageRoot, { recursive: true, force: true });
        const concurrent = await Promise.all([
          runRestoreAsync(restoreScript, environment),
          runRestoreAsync(restoreScript, environment),
        ]);
        for (const concurrentResult of concurrent) {
          expect(concurrentResult.status, concurrentResult.stderr).toBe(0);
          expect(concurrentResult.stdout).toContain(
            "windows-native-helper: restore complete",
          );
        }
        const finalResult = runRestore(restoreScript, environment);
        expect(finalResult.status, finalResult.stderr).toBe(0);
        expect(readFileSync(compiler)).toEqual(Buffer.from("tiny-csc\0\r\n", "utf8"));
        expect(
          readFileSync(
            join(
              packageRoot,
              "microsoft.netframework.referenceassemblies.net48.1.0.3",
              "build",
              ".NETFramework",
              "v4.8",
              "System.Core.dll",
            ),
            "utf8",
          ),
        ).toBe("system-core");
        expect(
          readdirSync(packageRoot).some((name) => name.endsWith(".tmp")),
        ).toBe(false);
      } finally {
        rmSync(fixtureRoot, { recursive: true, force: true });
      }
    },
    120_000,
  );

  it("keeps POSIX skips scoped to exactly two Windows integration cases", () => {
    const source = readRepositoryFile("test/native/native-build-contract.test.ts");
    expect(source.match(/\bit\.runIf\(/g)).toHaveLength(1);
    expect(source.match(/\bwindowsIt\(/g)).toHaveLength(2);
    expect(source).not.toMatch(/\b(?:it|describe)\.(?:skip|skipIf)\(/);
  });

  it("pins exclusive build, serialized restore, and trusted PowerShell contracts", () => {
    const build = readRepositoryFile("native/windows-job-helper/build.ps1");
    expect(build).toContain("[System.IO.FileMode]::CreateNew");
    expect(build).toContain("[System.IO.File]::Move");
    expect(build).not.toContain("[System.IO.File]::Copy");
    expect(build).toContain("windows-native-helper: native path contains a reparse point");
    expect(build).toContain("Remove-ExclusiveBuildRoot");
    expect(build).toContain("windows-native-helper: native build cleanup failed");
    expect(build).toContain(
      'Write-Output "windows-native-helper: generated protocol constants verified"',
    );

    const restore = readRepositoryFile(
      "native/windows-job-helper/restore-toolchain.ps1",
    );
    for (const fragment of [
      '"Local\\CodexAgentTools.WindowsJobHelper.ToolchainV1.',
      "[System.Threading.Mutex]",
      ".WaitOne()",
      "[System.Threading.AbandonedMutexException]",
      ".ReleaseMutex()",
    ]) {
      expect(restore).toContain(fragment);
    }

    const runner = readRepositoryFile("scripts/windows-native-helper.mjs");
    expect(runner).toContain('process.arch !== "x64"');
    expect(runner).toContain("process.env.SystemRoot");
    expect(runner).toContain('fail("invalid SystemRoot")');
    expect(runner).toContain("realpathSync.native");
    expect(runner).toContain(
      'join(systemRoot, "System32", "WindowsPowerShell", "v1.0", "powershell.exe")',
    );
    expect(runner).not.toContain('spawnSync("powershell.exe"');
  });

  it("provides only fixed package entrypoints for the native runner", () => {
    const packageJson = readRepositoryJson("package.json") as {
      scripts: Record<string, string>;
    };

    expect(packageJson.scripts).toMatchObject({
      "native:preflight": "node scripts/windows-native-helper.mjs preflight",
      "native:test:managed":
        "node scripts/windows-native-helper.mjs test-managed",
      "native:test:kernel": "node scripts/windows-native-helper.mjs test-kernel",
      "native:verify": "node scripts/windows-native-helper.mjs verify",
      "native:update-artifact":
        "node scripts/windows-native-helper.mjs update-artifact",
      "test:native": "node scripts/windows-native-helper.mjs test",
    });

    for (const name of [
      "native:preflight",
      "native:test:managed",
      "native:test:kernel",
      "native:verify",
      "native:update-artifact",
      "test:native",
    ]) {
      expect(packageJson.scripts[name]).not.toMatch(/override|bootstrap|refresh|fallback/i);
    }
    expect(packageJson.scripts).not.toHaveProperty("native:preflight:current");
  });

  it("ships fixed PowerShell and Node entrypoints without an override surface", () => {
    for (const path of [
      "native/windows-job-helper/restore-toolchain.ps1",
      "native/windows-job-helper/build.ps1",
      "scripts/windows-native-helper.mjs",
    ]) {
      const contents = readRepositoryFile(path);
      expect(contents.startsWith("\uFEFF")).toBe(false);
      expect(contents).not.toContain("\r\n");
    }

    const result = spawnSync(
      process.execPath,
      ["scripts/windows-native-helper.mjs", "restore", "--toolchain-override=x"],
      { cwd: repositoryRoot, encoding: "utf8" },
    );

    expect(result.status).toBe(1);
    expect(result.stdout).toBe("");
    expect(result.stderr).toBe("windows-native-helper: unsupported arguments\n");
  });
});
